require('dotenv').config();

const POSTGRESQL_DB = process.env.POSTGRESQL_DB
const POSTGRESQL_USERNAME = process.env.POSTGRESQL_USERNAME
const POSTGRESQL_PASSWORD = process.env.POSTGRESQL_PASSWORD
const POSTGRESQL_HOST = process.env.POSTGRESQL_HOST
const POSTGRESQL_PORT = 5432

const POSTGRESQL_CONNECTION_STRING = {
    database: POSTGRESQL_DB,
    username: POSTGRESQL_USERNAME,
    password: POSTGRESQL_PASSWORD,
    host: POSTGRESQL_HOST,
    port: POSTGRESQL_PORT,
}

export {
    POSTGRESQL_DB,
    POSTGRESQL_USERNAME,
    POSTGRESQL_PASSWORD,
    POSTGRESQL_HOST,
    POSTGRESQL_PORT,
    POSTGRESQL_CONNECTION_STRING,
}